fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address:     admin@example.com
    sender_name:    Example.com
  registration:
    confirmation:
      enabled:    true
      template:   FOSUser:Registration:email.txt.twig